'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Contracts() As DbSet(Of Contract)
    Public Overridable Property FlatIncomes() As DbSet(Of FlatIncome)
    Public Overridable Property Flats() As DbSet(Of Flat)
    Public Overridable Property Payments() As DbSet(Of Payment)
    Public Overridable Property Rents() As DbSet(Of Rent)
    Public Overridable Property Rooms() As DbSet(Of Room)
    Public Overridable Property RunningCosts() As DbSet(Of RunningCost)
    Public Overridable Property Tennants() As DbSet(Of Tennant)

End Class
