'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FlatIncome
    Public Property IncomeID As Integer
    Public Property Name As String
    Public Property [Date] As Nullable(Of Date)
    Public Property Amount As Nullable(Of Decimal)
    Public Property Remarks As String
    Public Property FlatID As Nullable(Of Integer)

    Public Overridable Property Flat As Flat

End Class
