'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Payment
    Public Property PaymentID As Integer
    Public Property TennantID As Nullable(Of Integer)
    Public Property Amount As Nullable(Of Decimal)
    Public Property PaymentDate As Nullable(Of Date)

    Public Overridable Property Tennant As Tennant

End Class
