'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Room
    Public Property RoomID As Integer
    Public Property FlatID As Nullable(Of Integer)
    Public Property Size As Nullable(Of Decimal)
    Public Property CalculationSize As Nullable(Of Decimal)
    Public Property Name As String

    Public Overridable Property Flat As Flat
    Public Overridable Property Contracts As ICollection(Of Contract) = New HashSet(Of Contract)

End Class
