'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tennant
    Public Property TennantID As Integer
    Public Property Name As String
    Public Property FlatID As Nullable(Of Integer)
    Public Property Image As Byte()
    Public Property Settled As Nullable(Of Boolean)

    Public Overridable Property Contracts As ICollection(Of Contract) = New HashSet(Of Contract)
    Public Overridable Property Flat As Flat
    Public Overridable Property Payments As ICollection(Of Payment) = New HashSet(Of Payment)

End Class
